require("catppuccin").setup({
  flavour = "mocha",
  color_overrides = {
    all = {
      text = "#a6adc8",
      subtext1 = "#a6adc8",
      subtext0 = "#9399b2",
      overlay2 = "#7f849c",
      overlay1 = "#686c82",
      overlay0 = "#6c7086",
      surface2 = "#555878",
      surface1 = "#45475a",
      surface0 = "#313244",
      base = "#0a0a0f",
      mantle = "#020203",
      crust = "#000000",
      none = "NONE",
    },
    mocha = {
      rosewater = "#6FB5A5",
      flamingo = "#bf616a",
      pink = "#C98D90",
      mauve = "#A49FB4",
      red = "#9f626e",
      maroon = "#C48B8F",
      peach = "#8C9EA3",
      yellow = "#C1747F",
      green = "#7F9A7E",
      teal = "#5B828C",
      sky = "#4E6C83",
      sapphire = "#3E586E",
      blue = "#5C6F83",
      lavender = "#8D8CAF",
    },
    macchiato = {
      rosewater = "#E2D4CC",
      flamingo = "#D8C1BD",
      pink = "#D4B0C7",
      mauve = "#B39EAD",
      red = "#B2828F",
      maroon = "#A4747F",
      peach = "#C19B82",
      yellow = "#D18C8C",
      green = "#7F9A7E",
      teal = "#769B96",
      sky = "#6F8D9E",
      sapphire = "#5E7486",
      blue = "#72809E",
      lavender = "#A5A3B3",
    },
    frappe = {
      rosewater = "#6FB5A5",
      flamingo = "#bf616a",
      pink = "#a3be8c",
      mauve = "#d08770",
      red = "#ebcb8b",
      maroon = "#b48ead",
      peach = "#d8dee9",
      yellow = "#eceff4",
      green = "#8fbcbb",
      teal = "#88c0d0",
      sky = "#81a1c1",
      sapphire = "#5e81ac",
      blue = "#eceff4",
      lavender = "#8D8CAF",
    },
    latte = {
      rosewater = "#3C3F4A",
      flamingo = "#EBA0AC",
      pink = "#C2B59B",
      mauve = "#CF8164",
      red = "#8296B0",
      maroon = "#A18DAF",
      peach = "#659EA2",
      yellow = "#B5B4C9",
      green = "#76A065",
      teal = "#EBA0AC",
      sky = "#C2B59B",
      sapphire = "#CF8164",
      blue = "#8296B0",
      lavender = "#A18DAF",
    },
  },
  custom_highlights = function(colors)
    return {
      Bufferline = { bg = colors.none },
      NvimTreeNormal = { bg = colors.none },
      NvimTreeFolderIcon = { fg = colors.surface2 },
      NvimTreeFolderName = { fg = colors.surface2 },
      NvimTreeEmptyFolderIcon = { fg = colors.surface2 },
      NvimTreeEmptyFolderName = { fg = colors.surface2 },
      NvimTreeOpenedFolderName = { fg = colors.flamingo },
      NvimTreeOpenedFolderIcon = { fg = colors.flamingo },
    }
  end,
  dim_inactive = {
    enabled = true,
    shade = "dark",
    percentage = 0.15,
  },
  transparent_background = true,
  term_colors = true,
  integrations = {
    nvimtree = true,
    cmp = true,
    gitsigns = true,
    telescope = true,
    treesitter = true,
    lsp_saga = true,
    mason = true,
    which_key = true,
    markdown = true,
    bufferline = true,
    lightspeed = true,
  },
})
