require("catppuccin").setup({
  flavour = "mocha",
  color_overrides = {
    all = {
      text = "#9c9eb4",
      subtext1 = "#a6adc3",
      subtext0 = "#9399ad",
      overlay2 = "#7f8497",
      overlay1 = "#686c7d",
      overlay0 = "#646782",
      surface2 = "#555873",
      surface1 = "#22232d",
      surface0 = "#0a0d0e",
      base = "#0a0a0f",
      mantle = "#020203",
      crust = "#000000",
      none = "NONE",
    },
    macchiato = {
      rosewater = "#a1e7d7",
      flamingo = "#f1939c",
      pink = "#fbbfc2",
      mauve = "#9baac4",
      red = "#d194a0",
      maroon = "#f6bdb7",
      peach = "#bed0d5",
      yellow = "#f3a6b1",
      green = "#b1ccb0",
      teal = "#8db4be",
      sky = "#9091a0",
      sapphire = "#a1b1b5",
      blue = "#aaafbf",
      lavender = "#b4b4cd",
    },
    frappe = {
      rosewater = "#79bfaf",
      flamingo = "#748787",
      pink = "#878c9b",
      mauve = "#73829c",
      red = "#757a92",
      maroon = "#8787aa",
      peach = "#96a8ad",
      yellow = "#858ea7",
      green = "#98b3ac",
      teal = "#5b7878",
      sky = "#686978",
      sapphire = "#486278",
      blue = "#8ca0b0",
      lavender = "#8c8ca5",
    },
  },
  custom_highlights = function(colors)
    return {
      Bufferline = { bg = colors.none },
      NvimTreeNormal = { bg = colors.none },
      NvimTreeFolderIcon = { fg = colors.surface2 },
      NvimTreeFolderName = { fg = colors.surface2 },
      NvimTreeEmptyFolderIcon = { fg = colors.surface2 },
      NvimTreeEmptyFolderName = { fg = colors.surface2 },
      NvimTreeOpenedFolderName = { fg = colors.flamingo },
      NvimTreeOpenedFolderIcon = { fg = colors.flamingo },
    }
  end,
  transparent_background = true,
  term_colors = true,
  integrations = {
    nvimtree = true,
    cmp = true,
    gitsigns = true,
    telescope = { enabled = true },
    treesitter = true,
    lsp_saga = true,
    mason = true,
    which_key = true,
    markdown = true,
    lightspeed = true,
    noice = true,
  },
})
