require("conform").setup({
  formatters = {
    coal_fmt = {
      command = "coal",
      args = { "fmt" },
      stdin = true,
    },
  },
  formatters_by_ft = {
    sh = { "shfmt" },
    elixir = { "mix" },
    go = { "gofmt" },
    python = { "ruff_fix", "ruff_format" },
    lua = { "stylua" },
    java = { "google-java-format" },
    typescriptreact = { "prettierd", "prettier", stop_after_first = true },
    javascriptreact = { "prettierd", "prettier", stop_after_first = true },
    typescript = { "prettierd", "prettier", stop_after_first = true },
    javascript = { "prettierd", "prettier", stop_after_first = true },
    scss = { "prettierd", "prettier", stop_after_first = true },
    css = { "prettierd", "prettier", stop_after_first = true },
    sql = { "sqlfluff" },
    proto = { "buf" },
    markdown = { "prettierd", "prettier", stop_after_first = true },
    html = { "prettierd", "prettier", stop_after_first = true },
    json = { "prettierd", "prettier", stop_after_first = true },
    toml = { "taplo" },
    yaml = { "prettierd" },
    just = { "just" },
    coal = { "coal_fmt" },
  },
  format_on_save = {
    timeout_ms = 500,
    lsp_fallback = true,
  },
})
