require("conform").setup({
  formatters_by_ft = {
    sh = { "shfmt" },
    elixir = { "mix" },
    go = { "gofmt" },
    python = { "ruff_fix", "ruff_format" },
    lua = { "stylua" },
    java = { "google-java-format" },
    typescriptreact = { { "prettierd", "prettier" } },
    javascriptreact = { { "prettierd", "prettier" } },
    typescript = { { "prettierd", "prettier" } },
    javascript = { { "prettierd", "prettier" } },
    scss = { { "prettierd", "prettier" } },
    css = { { "prettierd", "prettier" } },
    sql = { "sqlfluff" },
    proto = { "buf" },
    markdown = { { "prettierd", "prettier" } },
    html = { { "prettierd", "prettier" } },
    json = { { "prettierd", "prettier" } },
    toml = { "taplo" },
    yaml = { "prettierd" },
    just = { "just" },
  },
  format_on_save = {
    timeout_ms = 500,
    lsp_fallback = true,
  },
})
